In [7]:
import numpy as np
arrays = [np.random.randn(2, 3)for _ in range(8)]
np.stack(arrays, axis=0).shape




(8, 2, 3)

In [12]:
import numpy as np
np.stack(arrays, axis=1).shape
(2, 8, 3)

np.stack(arrays, axis=2).shape
(2, 3, 8)

x = np.array([2, 3, 4])
y = np.array([3, 4, 5])
np.stack((x, y))




array([[2, 3, 4],
       [3, 4, 5]])

In [10]:
#Numpy numpy.stack() function with axis parameter

import numpy as np
x = np.array([2, 3, 4])
y = np.array([3, 4, 5])
np.stack((x, y))

np.stack((x, y), axis=-1)


array([[2, 3],
       [3, 4],
       [4, 5]])

In [13]:
import numpy as np
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
print("Vertical stacking:\n", np.vstack((a, b)))
print("\nHorizontal stacking:\n", np.hstack((a, b)))
c = [5, 6]
print("\nColumn stacking:\n", np.column_stack((a, c)))
print("\nConcatenating to 2nd axis:\n", np.concatenate((a, b), 1))



Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]

Column stacking:
 [[1 2 5]
 [3 4 6]]

Concatenating to 2nd axis:
 [[1 2 5 6]
 [3 4 7 8]]
